module.exports = [
  {
    value: 'AK',
    cities: [
      { value: 'Anchorage' },
    ]
  },
  {
    value: 'AL',
    cities: [
      { value: 'Birmingham' },
      { value: 'Montgomery' },
      { value: 'Mobile' },
      { value: 'Huntsville' },
      { value: 'Tuscaloosa' },
      { value: 'Hoover' },
      { value: 'Dothan' },
      { value: 'Auburn' },
      { value: 'Decatur' },
      { value: 'Madison' },
      { value: 'Florence' },
      { value: 'Gadsden' },
    ]
  },
  {
    value: 'AR',
    cities: [
      { value: 'Little Rock' },
      { value: 'Fort Smith' },
      { value: 'Fayetteville' },
      { value: 'Springdale' },
      { value: 'Jonesboro' },
      { value: 'North Little Rock' },
      { value: 'Conway' },
      { value: 'Rogers' },
      { value: 'Pine Bluff' },
      { value: 'Bentonville' },
    ]
  },
  {
    value: 'AZ',
    cities: [
      { value: 'Phoenix' },
      { value: 'Tucson' },
      { value: 'Mesa' },
      { value: 'Chandler' },
      { value: 'Glendale' },
      { value: 'Scottsdale' },
      { value: 'Gilbert' },
      { value: 'Tempe' },
      { value: 'Peoria' },
      { value: 'Surprise' },
      { value: 'Yuma' },
      { value: 'Avondale' },
      { value: 'Goodyear' },
      { value: 'Flagstaff' },
      { value: 'Buckeye' },
      { value: 'Lake Havasu City' },
      { value: 'Casa Grande' },
      { value: 'Sierra Vista' },
      { value: 'Maricopa' },
      { value: 'Oro Valley' },
      { value: 'Prescott' },
      { value: 'Bullhead City' },
      { value: 'Prescott Valley' },
      { value: 'Marana' },
      { value: 'Apache Junction' },
    ]
  },
  {
    value: 'CA',
    cities: [
      { value: 'Los Angeles' },
      { value: 'San Diego' },
      { value: 'San Jose' },
      { value: 'San Francisco' },
      { value: 'Fresno' },
      { value: 'Sacramento' },
      { value: 'Long Beach' },
      { value: 'Oakland' },
      { value: 'Bakersfield' },
      { value: 'Anaheim' },
      { value: 'Santa Ana' },
      { value: 'Riverside' },
      { value: 'Stockton' },
      { value: 'Chula Vista' },
      { value: 'Irvine' },
      { value: 'Fremont' },
      { value: 'San Bernardino' },
      { value: 'Modesto' },
      { value: 'Fontana' },
      { value: 'Oxnard' },
      { value: 'Moreno Valley' },
      { value: 'Huntington Beach' },
      { value: 'Glendale' },
      { value: 'Santa Clarita' },
      { value: 'Garden Grove' },
      { value: 'Oceanside' },
      { value: 'Rancho Cucamonga' },
      { value: 'Santa Rosa' },
      { value: 'Ontario' },
      { value: 'Lancaster' },
      { value: 'Elk Grove' },
      { value: 'Corona' },
      { value: 'Palmdale' },
      { value: 'Salinas' },
      { value: 'Pomona' },
      { value: 'Hayward' },
      { value: 'Escondido' },
      { value: 'Torrance' },
      { value: 'Sunnyvale' },
      { value: 'Orange' },
      { value: 'Fullerton' },
      { value: 'Pasadena' },
      { value: 'Thousand Oaks' },
      { value: 'Visalia' },
      { value: 'Simi Valley' },
      { value: 'Concord' },
      { value: 'Roseville' },
      { value: 'Victorville' },
      { value: 'Santa Clara' },
      { value: 'Vallejo' },
      { value: 'Berkeley' },
      { value: 'El Monte' },
      { value: 'Downey' },
      { value: 'Costa Mesa' },
      { value: 'Inglewood' },
      { value: 'Carlsbad' },
      { value: 'San Buenaventura (Ventura)' },
      { value: 'Fairfield' },
      { value: 'West Covina' },
      { value: 'Murrieta' },
      { value: 'Richmond' },
      { value: 'Norwalk' },
      { value: 'Antioch' },
      { value: 'Temecula' },
      { value: 'Burbank' },
      { value: 'Daly City' },
      { value: 'Rialto' },
      { value: 'Santa Maria' },
      { value: 'El Cajon' },
      { value: 'San Mateo' },
      { value: 'Clovis' },
      { value: 'Compton' },
      { value: 'Jurupa Valley' },
      { value: 'Vista' },
      { value: 'South Gate' },
      { value: 'Mission Viejo' },
      { value: 'Vacaville' },
      { value: 'Carson' },
      { value: 'Hesperia' },
      { value: 'Santa Monica' },
      { value: 'Westminster' },
      { value: 'Redding' },
      { value: 'Santa Barbara' },
      { value: 'Chico' },
      { value: 'Newport Beach' },
      { value: 'San Leandro' },
      { value: 'San Marcos' },
      { value: 'Whittier' },
      { value: 'Hawthorne' },
      { value: 'Citrus Heights' },
      { value: 'Tracy' },
      { value: 'Alhambra' },
      { value: 'Livermore' },
      { value: 'Buena Park' },
      { value: 'Menifee' },
      { value: 'Hemet' },
      { value: 'Lakewood' },
      { value: 'Merced' },
      { value: 'Chino' },
      { value: 'Indio' },
      { value: 'Redwood City' },
      { value: 'Lake Forest' },
      { value: 'Napa' },
      { value: 'Tustin' },
      { value: 'Bellflower' },
      { value: 'Mountain View' },
      { value: 'Chino Hills' },
      { value: 'Baldwin Park' },
      { value: 'Alameda' },
      { value: 'Upland' },
      { value: 'San Ramon' },
      { value: 'Folsom' },
      { value: 'Pleasanton' },
      { value: 'Union City' },
      { value: 'Perris' },
      { value: 'Manteca' },
      { value: 'Lynwood' },
      { value: 'Apple Valley' },
      { value: 'Redlands' },
      { value: 'Turlock' },
      { value: 'Milpitas' },
      { value: 'Redondo Beach' },
      { value: 'Rancho Cordova' },
      { value: 'Yorba Linda' },
      { value: 'Palo Alto' },
      { value: 'Davis' },
      { value: 'Camarillo' },
      { value: 'Walnut Creek' },
      { value: 'Pittsburg' },
      { value: 'South San Francisco' },
      { value: 'Yuba City' },
      { value: 'San Clemente' },
      { value: 'Laguna Niguel' },
      { value: 'Pico Rivera' },
      { value: 'Montebello' },
      { value: 'Lodi' },
      { value: 'Madera' },
      { value: 'Santa Cruz' },
      { value: 'La Habra' },
      { value: 'Encinitas' },
      { value: 'Monterey Park' },
      { value: 'Tulare' },
      { value: 'Cupertino' },
      { value: 'Gardena' },
      { value: 'National City' },
      { value: 'Rocklin' },
      { value: 'Petaluma' },
      { value: 'Huntington Park' },
      { value: 'San Rafael' },
      { value: 'La Mesa' },
      { value: 'Arcadia' },
      { value: 'Fountain Valley' },
      { value: 'Diamond Bar' },
      { value: 'Woodland' },
      { value: 'Santee' },
      { value: 'Lake Elsinore' },
      { value: 'Porterville' },
      { value: 'Paramount' },
      { value: 'Eastvale' },
      { value: 'Rosemead' },
      { value: 'Hanford' },
      { value: 'Highland' },
      { value: 'Brentwood' },
      { value: 'Novato' },
      { value: 'Colton' },
      { value: 'Cathedral City' },
      { value: 'Delano' },
      { value: 'Yucaipa' },
      { value: 'Watsonville' },
      { value: 'Placentia' },
      { value: 'Glendora' },
      { value: 'Gilroy' },
      { value: 'Palm Desert' },
      { value: 'Cerritos' },
      { value: 'West Sacramento' },
      { value: 'Aliso Viejo' },
      { value: 'Poway' },
      { value: 'La Mirada' },
      { value: 'Rancho Santa Margarita' },
      { value: 'Cypress' },
      { value: 'Dublin' },
      { value: 'Covina' },
      { value: 'Azusa' },
      { value: 'Palm Springs' },
      { value: 'San Luis Obispo' },
      { value: 'Ceres' },
      { value: 'San Jacinto' },
      { value: 'Lincoln' },
      { value: 'Newark' },
      { value: 'Lompoc' },
      { value: 'El Centro' },
      { value: 'Danville' },
      { value: 'Bell Gardens' },
      { value: 'Coachella' },
      { value: 'Rancho Palos Verdes' },
      { value: 'San Bruno' },
      { value: 'Rohnert Park' },
      { value: 'Brea' },
      { value: 'La Puente' },
      { value: 'Campbell' },
      { value: 'San Gabriel' },
      { value: 'Beaumont' },
      { value: 'Morgan Hill' },
      { value: 'Culver City' },
      { value: 'Calexico' },
      { value: 'Stanton' },
      { value: 'La Quinta' },
      { value: 'Pacifica' },
      { value: 'Montclair' },
      { value: 'Oakley' },
      { value: 'Monrovia' },
      { value: 'Los Banos' },
      { value: 'Martinez' },
    ]
  },
  {
    value: 'CO',
    cities: [
      {value: 'Denver' },
      {value: 'Colorado Springs' },
      {value: 'Aurora' },
      {value: 'Fort Collins' },
      {value: 'Lakewood' },
      {value: 'Thornton' },
      {value: 'Arvada' },
      {value: 'Westminster' },
      {value: 'Pueblo' },
      {value: 'Centennial' },
      {value: 'Boulder' },
      {value: 'Greeley' },
      {value: 'Longmont' },
      {value: 'Loveland' },
      {value: 'Grand Junction' },
      {value: 'Broomfield' },
      {value: 'Castle Rock' },
      {value: 'Commerce City' },
      {value: 'Parker' },
      {value: 'Littleton' },
      {value: 'Northglenn' },
    ]
  },
  {
    value: 'CT',
    cities: [
      { value: 'Bridgeport' },
      { value: 'New Haven' },
      { value: 'Stamford' },
      { value: 'Hartford' },
      { value: 'Waterbury' },
      { value: 'Norwalk' },
      { value: 'Danbury' },
      { value: 'New Britain' },
      { value: 'Meriden' },
      { value: 'Bristol' },
      { value: 'West Haven' },
      { value: 'Milford' },
      { value: 'Middletown' },
      { value: 'Norwich' },
      { value: 'Shelton' },
    ]
  },
  {
    value: 'DC',
    cities: [
      { value: 'Washington' }
    ]
  },
  {
    value: 'DE',
    cities: [
      { value: 'Wilmington' },
      { value: 'Dover' },
    ]
  },
  {
    value: 'FL',
    cities: [
      { value: 'Jacksonville' },
      { value: 'Miami' },
      { value: 'Tampa' },
      { value: 'Orlando' },
      { value: 'St. Petersburg' },
      { value: 'Hialeah' },
      { value: 'Tallahassee' },
      { value: 'Fort Lauderdale' },
      { value: 'Port St. Lucie' },
      { value: 'Cape Coral' },
      { value: 'Pembroke Pines' },
      { value: 'Hollywood' },
      { value: 'Miramar' },
      { value: 'Gainesville' },
      { value: 'Coral Springs' },
      { value: 'Miami Gardens' },
      { value: 'Clearwater' },
      { value: 'Palm Bay' },
      { value: 'Pompano Beach' },
      { value: 'West Palm Beach' },
      { value: 'Lakeland' },
      { value: 'Davie' },
      { value: 'Miami Beach' },
      { value: 'Sunrise' },
      { value: 'Plantation' },
      { value: 'Boca Raton' },
      { value: 'Deltona' },
      { value: 'Largo' },
      { value: 'Deerfield Beach' },
      { value: 'Palm Coast' },
      { value: 'Melbourne' },
      { value: 'Boynton Beach' },
      { value: 'Lauderhill' },
      { value: 'Weston' },
      { value: 'Fort Myers' },
      { value: 'Kissimmee' },
      { value: 'Homestead' },
      { value: 'Tamarac' },
      { value: 'Delray Beach' },
      { value: 'Daytona Beach' },
      { value: 'North Miami' },
      { value: 'Wellington' },
      { value: 'North Port' },
      { value: 'Jupiter' },
      { value: 'Ocala' },
      { value: 'Port Orange' },
      { value: 'Margate' },
      { value: 'Coconut Creek' },
      { value: 'Sanford' },
      { value: 'Sarasota' },
      { value: 'Pensacola' },
      { value: 'Bradenton' },
      { value: 'Palm Beach Gardens' },
      { value: 'Pinellas Park' },
      { value: 'Coral Gables' },
      { value: 'Doral' },
      { value: 'Bonita Springs' },
      { value: 'Apopka' },
      { value: 'Titusville' },
      { value: 'North Miami Beach' },
      { value: 'Oakland Park' },
      { value: 'Fort Pierce' },
      { value: 'North Lauderdale' },
      { value: 'Cutler Bay' },
      { value: 'Altamonte Springs' },
      { value: 'St. Cloud' },
      { value: 'Greenacres' },
      { value: 'Ormond Beach' },
      { value: 'Ocoee' },
      { value: 'Hallandale Beach' },
      { value: 'Winter Garden' },
      { value: 'Aventura' },
    ]
  },
  {
    value: 'GA',
    cities: [
      { value: 'Atlanta' },
      { value: 'Columbus' },
      { value: 'Augusta-Richmond County' },
      { value: 'Savannah' },
      { value: 'Athens-Clarke County' },
      { value: 'Sandy Springs' },
      { value: 'Roswell' },
      { value: 'Macon' },
      { value: 'Johns Creek' },
      { value: 'Albany' },
      { value: 'Warner Robins' },
      { value: 'Alpharetta' },
      { value: 'Marietta' },
      { value: 'Valdosta' },
      { value: 'Smyrna' },
      { value: 'Dunwoody' },
    ]
  },
  {
    value: 'HI',
    cities: [
      { value: 'Honolulu' },
    ]
  },
  {
    value: 'ID',
    cities: [
      { value: 'Boise City' },
      { value: 'Nampa' },
      { value: 'Meridian' },
      { value: 'Idaho Falls' },
      { value: 'Pocatello' },
      { value: 'Caldwell' },
      { value: 'Coeur d\'Alene' },
      { value: 'Twin Falls' },
    ]
  },
  {
    value: 'IL',
    cities: [
       { value: 'Chicago' },
       { value: 'Aurora' },
       { value: 'Rockford' },
       { value: 'Joliet' },
       { value: 'Naperville' },
       { value: 'Springfield' },
       { value: 'Peoria' },
       { value: 'Elgin' },
       { value: 'Waukegan' },
       { value: 'Cicero' },
       { value: 'Champaign' },
       { value: 'Bloomington' },
       { value: 'Arlington Heights' },
       { value: 'Evanston' },
       { value: 'Decatur' },
       { value: 'Schaumburg' },
       { value: 'Bolingbrook' },
       { value: 'Palatine' },
       { value: 'Skokie' },
       { value: 'Des Plaines' },
       { value: 'Orland Park' },
       { value: 'Tinley Park' },
       { value: 'Oak Lawn' },
       { value: 'Berwyn' },
       { value: 'Mount Prospect' },
       { value: 'Normal' },
       { value: 'Wheaton' },
       { value: 'Hoffman Estates' },
       { value: 'Oak Park' },
       { value: 'Downers Grove' },
       { value: 'Elmhurst' },
       { value: 'Glenview' },
       { value: 'DeKalb' },
       { value: 'Lombard' },
       { value: 'Belleville' },
       { value: 'Moline' },
       { value: 'Buffalo Grove' },
       { value: 'Bartlett' },
       { value: 'Urbana' },
       { value: 'Quincy' },
       { value: 'Crystal Lake' },
       { value: 'Plainfield' },
       { value: 'Streamwood' },
       { value: 'Carol Stream' },
       { value: 'Romeoville' },
       { value: 'Rock Island' },
       { value: 'Hanover Park' },
       { value: 'Carpentersville' },
       { value: 'Wheeling' },
       { value: 'Park Ridge' },
       { value: 'Addison' },
       { value: 'Calumet City' },
    ]
  },
  {
    value: 'IN',
    cities: [
      { value: 'Indianapolis' },
      { value: 'Fort Wayne' },
      { value: 'Evansville' },
      { value: 'South Bend' },
      { value: 'Carmel' },
      { value: 'Bloomington' },
      { value: 'Fishers' },
      { value: 'Hammond' },
      { value: 'Gary' },
      { value: 'Muncie' },
      { value: 'Lafayette' },
      { value: 'Terre Haute' },
      { value: 'Kokomo' },
      { value: 'Anderson' },
      { value: 'Noblesville' },
      { value: 'Greenwood' },
      { value: 'Elkhart' },
      { value: 'Mishawaka' },
      { value: 'Lawrence' },
      { value: 'Jeffersonville' },
      { value: 'Columbus' },
      { value: 'Portage' },
    ]
  },
  {
    value: 'IO',
    cities: [
      { value: 'Des Moines' },
      { value: 'Cedar Rapids' },
      { value: 'Davenport' },
      { value: 'Sioux City' },
      { value: 'Iowa City' },
      { value: 'Waterloo' },
      { value: 'Council Bluffs' },
      { value: 'Ames' },
      { value: 'West Des Moines' },
      { value: 'Dubuque' },
      { value: 'Ankeny' },
      { value: 'Urbandale' },
      { value: 'Cedar Falls' },
    ]
  },
  {
    value: 'KS',
    cities: [
      { value: 'Wichita' },
      { value: 'Overland Park' },
      { value: 'Kansas City' },
      { value: 'Olathe' },
      { value: 'Topeka' },
      { value: 'Lawrence' },
      { value: 'Shawnee' },
      { value: 'Manhattan' },
      { value: 'Lenexa' },
      { value: 'Salina' },
      { value: 'Hutchinson' },
    ]
  },
  {
    value: 'KY',
    cities: [
      { value: 'Louisville/Jefferson County' },
      { value: 'Lexington-Fayette' },
      { value: 'Bowling Green' },
      { value: 'Owensboro' },
      { value: 'Covington' },
    ]
  },
  {
    value: 'LA',
    cities: [
      { value: 'New Orleans' },
      { value: 'Baton Rouge' },
      { value: 'Shreveport' },
      { value: 'Lafayette' },
      { value: 'Lake Charles' },
      { value: 'Kenner' },
      { value: 'Bossier City' },
      { value: 'Monroe' },
      { value: 'Alexandria' },
    ]
  },
  {
    value: 'MA',
    cities: [
      { value: 'Boston' },
      { value: 'Worcester' },
      { value: 'Springfield' },
      { value: 'Lowell' },
      { value: 'Cambridge' },
      { value: 'New Bedford' },
      { value: 'Brockton' },
      { value: 'Quincy' },
      { value: 'Lynn' },
      { value: 'Fall River' },
      { value: 'Newton' },
      { value: 'Lawrence' },
      { value: 'Somerville' },
      { value: 'Waltham' },
      { value: 'Haverhill' },
      { value: 'Malden' },
      { value: 'Medford' },
      { value: 'Taunton' },
      { value: 'Chicopee' },
      { value: 'Weymouth Town' },
      { value: 'Revere' },
      { value: 'Peabody' },
      { value: 'Methuen' },
      { value: 'Barnstable Town' },
      { value: 'Pittsfield' },
      { value: 'Attleboro' },
      { value: 'Everett' },
      { value: 'Salem' },
      { value: 'Westfield' },
      { value: 'Leominster' },
      { value: 'Fitchburg' },
      { value: 'Beverly' },
      { value: 'Holyoke' },
      { value: 'Marlborough' },
      { value: 'Woburn' },
      { value: 'Chelsea' },
    ]
  },
  {
    value: 'MD',
    cities: [
      { value: 'Baltimore' },
      { value: 'Frederick' },
      { value: 'Rockville' },
      { value: 'Gaithersburg' },
      { value: 'Bowie' },
      { value: 'Hagerstown' },
      { value: 'Annapolis' },
    ]
  },
  {
    value: 'ME',
    cities: [
      { value: 'Portland' },
    ]
  },
  {
    value: 'MI',
    cities: [
      { value: 'Detroit' },
      { value: 'Grand Rapids' },
      { value: 'Warren' },
      { value: 'Sterling Heights' },
      { value: 'Ann Arbor' },
      { value: 'Lansing' },
      { value: 'Flint' },
      { value: 'Dearborn' },
      { value: 'Livonia' },
      { value: 'Westland' },
      { value: 'Troy' },
      { value: 'Farmington Hills' },
      { value: 'Kalamazoo' },
      { value: 'Wyoming' },
      { value: 'Southfield' },
      { value: 'Rochester Hills' },
      { value: 'Taylor' },
      { value: 'Pontiac' },
      { value: 'St. Clair Shores' },
      { value: 'Royal Oak' },
      { value: 'Novi' },
      { value: 'Dearborn Heights' },
      { value: 'Battle Creek' },
      { value: 'Saginaw' },
      { value: 'Kentwood' },
      { value: 'East Lansing' },
      { value: 'Roseville' },
      { value: 'Portage' },
      { value: 'Midland' },
      { value: 'Lincoln Park' },
      { value: 'Muskegon' },
    ]
  },
  {
    value: 'MN',
    cities: [
      { value: 'Minneapolis' },
      { value: 'St. Paul' },
      { value: 'Rochester' },
      { value: 'Duluth' },
      { value: 'Bloomington' },
      { value: 'Brooklyn Park' },
      { value: 'Plymouth' },
      { value: 'St. Cloud' },
      { value: 'Eagan' },
      { value: 'Woodbury' },
      { value: 'Maple Grove' },
      { value: 'Eden Prairie' },
      { value: 'Coon Rapids' },
      { value: 'Burnsville' },
      { value: 'Blaine' },
      { value: 'Lakeville' },
      { value: 'Minnetonka' },
      { value: 'Apple Valley' },
      { value: 'Edina' },
      { value: 'St. Louis Park' },
      { value: 'Mankato' },
      { value: 'Maplewood' },
      { value: 'Moorhead' },
      { value: 'Shakopee' },
    ]
  },
  {
    value: 'MO',
    cities: [
      { value: 'Kansas City' },
      { value: 'St. Louis' },
      { value: 'Springfield' },
      { value: 'Independence' },
      { value: 'Columbia' },
      { value: 'Lee\'s Summit' },
      { value: 'O\'Fallon' },
      { value: 'St. Joseph' },
      { value: 'St. Charles' },
      { value: 'St. Peters' },
      { value: 'Blue Springs' },
      { value: 'Florissant' },
      { value: 'Joplin' },
      { value: 'Chesterfield' },
      { value: 'Jefferson City' },
      { value: 'Cape Girardeau' },
    ]
  },
  {
    value: 'MS',
    cities: [
      { value: 'Jackson' },
      { value: 'Gulfport' },
      { value: 'Southaven' },
      { value: 'Hattiesburg' },
      { value: 'Biloxi' },
      { value: 'Meridian' },
    ]
  },
  {
    value: 'MT',
    cities: [
      { value: 'Billings' },
      { value: 'Missoula' },
      { value: 'Great Falls' },
      { value: 'Bozeman' },
    ]
  },
  {
    value: 'NC',
    cities: [
      { value: 'Charlotte' },
      { value: 'Raleigh' },
      { value: 'Greensboro' },
      { value: 'Durham' },
      { value: 'Winston-Salem' },
      { value: 'Fayetteville' },
      { value: 'Cary' },
      { value: 'Wilmington' },
      { value: 'High Point' },
      { value: 'Greenville' },
      { value: 'Asheville' },
      { value: 'Concord' },
      { value: 'Gastonia' },
      { value: 'Jacksonville' },
      { value: 'Chapel Hill' },
      { value: 'Rocky Mount' },
      { value: 'Burlington' },
      { value: 'Wilson' },
      { value: 'Huntersville' },
      { value: 'Kannapolis' },
      { value: 'Apex' },
      { value: 'Hickory' },
      { value: 'Goldsboro' },
    ]
  },
  {
    value: 'ND',
    cities: [
      { value: 'Fargo' },
      { value: 'Bismarck' },
      { value: 'Grand Forks' },
      { value: 'Minot' },
    ]
  },
  {
    value: 'NE',
    cities: [
      { value: 'Omaha' },
      { value: 'Lincoln' },
      { value: 'Bellevue' },
      { value: 'Grand Island' },
    ]
  },
  {
    value: 'NH',
    cities: [
      { value: 'Manchester' },
      { value: 'Nashua' },
      { value: 'Concord' },
    ]
  },
  {
    value: 'NJ',
    cities: [
      { value: 'Newark' },
      { value: 'Jersey City' },
      { value: 'Paterson' },
      { value: 'Elizabeth' },
      { value: 'Clifton' },
      { value: 'Trenton' },
      { value: 'Camden' },
      { value: 'Passaic' },
      { value: 'Union City' },
      { value: 'Bayonne' },
      { value: 'East Orange' },
      { value: 'Vineland' },
      { value: 'New Brunswick' },
      { value: 'Hoboken' },
      { value: 'Perth Amboy' },
      { value: 'West New York' },
      { value: 'Plainfield' },
      { value: 'Hackensack' },
      { value: 'Sayreville' },
      { value: 'Kearny' },
      { value: 'Linden' },
      { value: 'Atlantic City' },
    ]
  },
  {
    value: 'NM',
    cities: [
      { value: 'Albuquerque' },
      { value: 'Las Cruces' },
      { value: 'Rio Rancho' },
      { value: 'Santa Fe' },
      { value: 'Roswell' },
      { value: 'Farmington' },
      { value: 'Clovis' },
    ]
  },
  {
    value: 'NV',
    cities: [
      { value: 'Las Vegas' },
      { value: 'Henderson' },
      { value: 'Reno' },
      { value: 'North Las Vegas' },
      { value: 'Sparks' },
      { value: 'Carson City' },
    ]
  },
  {
    value: 'NY',
    cities: [
      { value: 'New York' },
      { value: 'Buffalo' },
      { value: 'Rochester' },
      { value: 'Yonkers' },
      { value: 'Syracuse' },
      { value: 'Albany' },
      { value: 'New Rochelle' },
      { value: 'Mount Vernon' },
      { value: 'Schenectady' },
      { value: 'Utica' },
      { value: 'White Plains' },
      { value: 'Hempstead' },
      { value: 'Troy' },
      { value: 'Niagara Falls' },
      { value: 'Binghamton' },
      { value: 'Freeport' },
      { value: 'Valley Stream' },
    ]
  },
  {
    value: 'OH',
    cities: [
      { value: 'Columbus' },
      { value: 'Cleveland' },
      { value: 'Cincinnati' },
      { value: 'Toledo' },
      { value: 'Akron' },
      { value: 'Dayton' },
      { value: 'Parma' },
      { value: 'Canton' },
      { value: 'Youngstown' },
      { value: 'Lorain' },
      { value: 'Hamilton' },
      { value: 'Springfield' },
      { value: 'Kettering' },
      { value: 'Elyria' },
      { value: 'Lakewood' },
      { value: 'Cuyahoga Falls' },
      { value: 'Middletown' },
      { value: 'Euclid' },
      { value: 'Newark' },
      { value: 'Mansfield' },
      { value: 'Mentor' },
      { value: 'Beavercreek' },
      { value: 'Cleveland Heights' },
      { value: 'Strongsville' },
      { value: 'Dublin' },
      { value: 'Fairfield' },
      { value: 'Findlay' },
      { value: 'Warren' },
      { value: 'Lancaster' },
      { value: 'Lima' },
      { value: 'Huber Heights' },
      { value: 'Westerville' },
      { value: 'Marion' },
      { value: 'Grove City' },
    ]
  },
  {
    value: 'OK',
    cities: [
      { value: 'Oklahoma City' },
      { value: 'Tulsa' },
      { value: 'Norman' },
      { value: 'Broken Arrow' },
      { value: 'Lawton' },
      { value: 'Edmond' },
      { value: 'Moore' },
      { value: 'Midwest City' },
      { value: 'Enid' },
      { value: 'Stillwater' },
      { value: 'Muskogee' },
    ]
  },
  {
    value: 'OR',
    cities: [
      { value: 'Portland' },
      { value: 'Eugene' },
      { value: 'Salem' },
      { value: 'Gresham' },
      { value: 'Hillsboro' },
      { value: 'Beaverton' },
      { value: 'Bend' },
      { value: 'Medford' },
      { value: 'Springfield' },
      { value: 'Corvallis' },
      { value: 'Albany' },
      { value: 'Tigard' },
      { value: 'Lake Oswego' },
      { value: 'Keizer' },
    ]
  },
  {
    value: 'PA',
    cities: [
      { value: 'Philadelphia' },
      { value: 'Pittsburgh' },
      { value: 'Allentown' },
      { value: 'Erie' },
      { value: 'Reading' },
      { value: 'Scranton' },
      { value: 'Bethlehem' },
      { value: 'Lancaster' },
      { value: 'Harrisburg' },
      { value: 'Altoona' },
      { value: 'York' },
      { value: 'State College' },
      { value: 'Wilkes-Barre' },
    ]
  },
  {
    value: 'RI',
    cities: [
      { value: 'Providence' },
      { value: 'Warwick' },
      { value: 'Cranston' },
      { value: 'Pawtucket' },
      { value: 'East Providence' },
      { value: 'Woonsocket' },
    ]
  },
  {
    value: 'SC',
    cities: [
      { value: 'Columbia' },
      { value: 'Charleston' },
      { value: 'North Charleston' },
      { value: 'Mount Pleasant' },
      { value: 'Rock Hill' },
      { value: 'Greenville' },
      { value: 'Summerville' },
      { value: 'Sumter' },
      { value: 'Goose Creek' },
      { value: 'Hilton Head Island' },
      { value: 'Florence' },
      { value: 'Spartanburg' },
    ]
  },
  {
    value: 'SD',
    cities: [
      { value: 'Sioux Falls' },
      { value: 'Rapid City' },
    ]
  },
  {
    value: 'TN',
    cities: [
      { value: 'Memphis' },
      { value: 'Nashville-Davidson' },
      { value: 'Knoxville' },
      { value: 'Chattanooga' },
      { value: 'Clarksville' },
      { value: 'Murfreesboro' },
      { value: 'Jackson' },
      { value: 'Franklin' },
      { value: 'Johnson City' },
      { value: 'Bartlett' },
      { value: 'Hendersonville' },
      { value: 'Kingsport' },
      { value: 'Collierville' },
      { value: 'Cleveland' },
      { value: 'Smyrna' },
      { value: 'Germantown' },
      { value: 'Brentwood' },
      ]
  },
  {
    value: 'TX',
    cities: [
      { value: 'Houston' },
      { value: 'San Antonio' },
      { value: 'Dallas' },
      { value: 'Austin' },
      { value: 'Fort Worth' },
      { value: 'El Paso' },
      { value: 'Arlington' },
      { value: 'Corpus Christi' },
      { value: 'Plano' },
      { value: 'Laredo' },
      { value: 'Lubbock' },
      { value: 'Garland' },
      { value: 'Irving' },
      { value: 'Amarillo' },
      { value: 'Grand Prairie' },
      { value: 'Brownsville' },
      { value: 'Pasadena' },
      { value: 'McKinney' },
      { value: 'Mesquite' },
      { value: 'McAllen' },
      { value: 'Killeen' },
      { value: 'Frisco' },
      { value: 'Waco' },
      { value: 'Carrollton' },
      { value: 'Denton' },
      { value: 'Midland' },
      { value: 'Abilene' },
      { value: 'Beaumont' },
      { value: 'Round Rock' },
      { value: 'Odessa' },
      { value: 'Wichita Falls' },
      { value: 'Richardson' },
      { value: 'Lewisville' },
      { value: 'Tyler' },
      { value: 'College Station' },
      { value: 'Pearland' },
      { value: 'San Angelo' },
      { value: 'Allen' },
      { value: 'League City' },
      { value: 'Sugar Land' },
      { value: 'Longview' },
      { value: 'Edinburg' },
      { value: 'Mission' },
      { value: 'Bryan' },
      { value: 'Baytown' },
      { value: 'Pharr' },
      { value: 'Temple' },
      { value: 'Missouri City' },
      { value: 'Flower Mound' },
      { value: 'Harlingen' },
      { value: 'North Richland Hills' },
      { value: 'Victoria' },
      { value: 'Conroe' },
      { value: 'New Braunfels' },
      { value: 'Mansfield' },
      { value: 'Cedar Park' },
      { value: 'Rowlett' },
      { value: 'Port Arthur' },
      { value: 'Euless' },
      { value: 'Georgetown' },
      { value: 'Pflugerville' },
      { value: 'DeSoto' },
      { value: 'San Marcos' },
      { value: 'Grapevine' },
      { value: 'Bedford' },
      { value: 'Galveston' },
      { value: 'Cedar Hill' },
      { value: 'Texas City' },
      { value: 'Wylie' },
      { value: 'Haltom City' },
      { value: 'Keller' },
      { value: 'Coppell' },
      { value: 'Rockwall' },
      { value: 'Huntsville' },
      { value: 'Duncanville' },
      { value: 'Sherman' },
      { value: 'The Colony' },
      { value: 'Burleson' },
      { value: 'Hurst' },
      { value: 'Lancaster' },
      { value: 'Texarkana' },
      { value: 'Friendswood' },
      { value: 'Weslaco' },
    ]
  },
  {
    value: 'UT',
    cities: [
      { value: 'Salt Lake City' },
      { value: 'West Valley City' },
      { value: 'Provo' },
      { value: 'West Jordan' },
      { value: 'Orem' },
      { value: 'Sandy' },
      { value: 'Ogden' },
      { value: 'St. George' },
      { value: 'Layton' },
      { value: 'Taylorsville' },
      { value: 'South Jordan' },
      { value: 'Lehi' },
      { value: 'Logan' },
      { value: 'Murray' },
      { value: 'Draper' },
      { value: 'Bountiful' },
      { value: 'Riverton' },
      { value: 'Roy' },
    ]
  },
  {
    value: 'VA',
    cities: [
      { value: 'Virginia Beach' },
      { value: 'Norfolk' },
      { value: 'Chesapeake' },
      { value: 'Richmond' },
      { value: 'Newport News' },
      { value: 'Alexandria' },
      { value: 'Hampton' },
      { value: 'Roanoke' },
      { value: 'Portsmouth' },
      { value: 'Suffolk' },
      { value: 'Lynchburg' },
      { value: 'Harrisonburg' },
      { value: 'Leesburg' },
      { value: 'Charlottesville' },
      { value: 'Danville' },
      { value: 'Blacksburg' },
      { value: 'Manassas' },
    ]
  },
  {
    value: 'VT',
    cities: [
      { value: 'Burlington', }
    ]
  },
  {
    value: 'WA',
    cities: [
      { value: 'Seattle' },
      { value: 'Spokane' },
      { value: 'Tacoma' },
      { value: 'Vancouver' },
      { value: 'Bellevue' },
      { value: 'Kent' },
      { value: 'Everett' },
      { value: 'Renton' },
      { value: 'Yakima' },
      { value: 'Federal Way' },
      { value: 'Spokane Valley' },
      { value: 'Bellingham' },
      { value: 'Kennewick' },
      { value: 'Auburn' },
      { value: 'Pasco' },
      { value: 'Marysville' },
      { value: 'Lakewood' },
      { value: 'Redmond' },
      { value: 'Shoreline' },
      { value: 'Richland' },
      { value: 'Kirkland' },
      { value: 'Burien' },
      { value: 'Sammamish' },
      { value: 'Olympia' },
      { value: 'Lacey' },
      { value: 'Edmonds' },
      { value: 'Bremerton' },
      { value: 'Puyallup' },
    ]
  },
  {
    value: 'WI',
    cities: [
      { value: 'Milwaukee' },
      { value: 'Madison' },
      { value: 'Green Bay' },
      { value: 'Kenosha' },
      { value: 'Racine' },
      { value: 'Appleton' },
      { value: 'Waukesha' },
      { value: 'Eau Claire' },
      { value: 'Oshkosh' },
      { value: 'Janesville' },
      { value: 'West Allis' },
      { value: 'La Crosse' },
      { value: 'Sheboygan' },
      { value: 'Wauwatosa' },
      { value: 'Fond du Lac' },
      { value: 'New Berlin' },
      { value: 'Wausau' },
      { value: 'Brookfield' },
      { value: 'Greenfield' },
      { value: 'Beloit' },
    ]
  },
  {
    value: 'WY',
    cities: [
      { value: 'Cheyenne' },
      { value: 'Casper' },
    ]
  },
  {
    value: 'MV',
    cities: [
      { value: 'Charleston' },
      { value: 'Huntington' },
    ]
  },
]